name: Github Action Deployment

on:
  workflow_dispatch:
    inputs:
       Object_Code_choice: 
         type: choice
         description: 'Select the Object_Code'
         options:
         - None
         - All
         - A15
         - A43
         - A836
         - A215

       Child_Object_Code_Choice:
         type: choice
         description: ' Select the Child_object_code'
         options:
         - None
         - E01
         - E90
         - E66

       Workflow_Type_Choice: 
         type: choice
         description: 'Select WORKFLOW'
         required: true
         options:
          - ICD
          - Harness

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'  
      
    - name: Create Folder Structure
      run: |
        mkdir -p "https://github.com/suchita903/Demo_2024/#${{ env.WORKSPACE_URL }}/Input"
        
        if [ "$WORKFLOW" = "ICD" ]; then
            mv Build_xml "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv Build_tsv "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv ICD "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv GMLogic_ICD_Input "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
        else
            mv Build_tsv "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv Build_tsv "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv ICD "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv GMLogic_Harness_Input "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv Master_Pinout_Input "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
            mv UGnetlist_Input "https://github.com/suchita903/Demo123/#${{ env.WORKSPACE_URL }}/Inputs"
        fi

    - name: Zipping Files
      run: |
        # Create a zip file containing Inputs, Output, and Logs directories
        zip -r EIO_Config_Tool_Artifacts.zip Inputs Output Logs
        echo "********** Artifact zip created...! **********"
